# Generated by Django 4.1.2 on 2022-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
